### ISSUE TITLE
Absence of bias terms in imu config parameters

### ISSUE THREAD

**Issue by trunc8** [HKUST-Aerial-Robotics/VINS-Fusion#163]
These are the only IMU config parameters used by VINS-Fusion
```yaml
#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 7.9323744944112216e+00          # accelerometer measurement noise standard deviation. 
gyr_n: 3.9534459926755474e+00         # gyroscope measurement noise standard deviation.     
acc_w: 5.1765537212645074e-01        # accelerometer bias random work noise standard deviation.  
gyr_w: 4.8477797168896648e-03       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude
```
All of these are std devn parameters. How does the algorithm deal with biases in gyroscope and accelerometer if they are not taken input explicitly?
Is it advised to create another ROS topic to subtract the biases then?
