### ISSUE TITLE
[Transform IMU data To Camera Frame for VISN FUSION]

### ISSUE THREAD

**Issue by leechangyo** [HKUST-Aerial-Robotics/VINS-Fusion#190]
Hi Developer, 
i try to use your package to my research and i have sensor configuration system is like below link

https://gas.graviti.cn/dataset/hello-dataset/LIO_SAM

but i mounted camera to robot instead of lidar and try to use your package it doesn't work(camera pose fly out)

 i try to change imu data transformed to camera optical coordinate but it still doesn't work well

let me attach my code how i did a try(literally use the way to transform imu data from lio sam) 

```c++
void imu_callback(const sensor_msgs::ImuConstPtr &imu_msg)
{
    // CREATED BY CHAN
    sensor_msgs::Imu ThisImu = *imu_msg;
    if(IMU_ORIENTATION_CONVERT_NEED=="True")
    {
        ThisImu = imuConverter(*imu_msg);
        std::cout << "Converting IMU" << std::endl;
    }
    else
    {
        ThisImu= *imu_msg;
    }
    // std::cout << " imu reading "<< std::endl;
    double t = ThisImu.header.stamp.toSec();//讲头文件中的时间戳转换为s
    double dx = ThisImu.linear_acceleration.x;
    double dy = ThisImu.linear_acceleration.y;
    double dz = ThisImu.linear_acceleration.z;
    double rx = ThisImu.angular_velocity.x;
    double ry = ThisImu.angular_velocity.y;
    double rz = ThisImu.angular_velocity.z;
    Eigen::Vector3d acc(dx, dy, dz);
    Eigen::Vector3d gyr(rx, ry, rz);
    estimator->inputIMU(t, acc, gyr);
```

```c++
sensor_msgs::Imu imuConverter(const sensor_msgs::Imu& imu_in)
{
    sensor_msgs::Imu imu_out = imu_in;

    // rotate acceleration
    Eigen::Vector3d acc(imu_in.linear_acceleration.x, imu_in.linear_acceleration.y, imu_in.linear_acceleration.z);

    /* Created by chan */
    Eigen::Matrix3d base_to_optical; // it can be optical to base too 
    base_to_optical << 0,0,1,
                       -1,0,0,
                       0, -1, 0;
    
    /*  */
    // Rotate Acceleration
    acc = extRot * acc;
    /* CREATEBD CHAN  */
    acc = base_to_optical * acc;
    // acc = base_to_optical * acc;
    /*  */
    imu_out.linear_acceleration.x = acc.x();
    imu_out.linear_acceleration.y = acc.y();
    imu_out.linear_acceleration.z = acc.z();

    // Rotate Gyroscope
    Eigen::Vector3d gyr(imu_in.angular_velocity.x, imu_in.angular_velocity.y, imu_in.angular_velocity.z);
    gyr = extRot * gyr;
    /* CREATED BY CHAN */
    gyr = base_to_optical * gyr;
    // gyr = base_to_optical * gyr;
    /*  */
    imu_out.angular_velocity.x = gyr.x();
    imu_out.angular_velocity.y = gyr.y();
    imu_out.angular_velocity.z = gyr.z();

    // rotate roll pitch yaw
    Eigen::Quaterniond q_from(imu_in.orientation.w, imu_in.orientation.x, imu_in.orientation.y, imu_in.orientation.z);
    // Eigen::Matrix3d Rotate_Q = q_from.toRotationMatrix() * extRot;
    // Eigen::Quaterniond q_final(Rotate_Q);

    // Eigen::Quaterniond q_final = q_from;
    Eigen::Quaterniond q_final = q_from * extQRPY;
    imu_out.orientation.x = q_final.x();
    imu_out.orientation.y = q_final.y();
    imu_out.orientation.z = q_final.z();
    imu_out.orientation.w = q_final.w();

    // Catch Error
    if (sqrt(q_final.x() * q_final.x() + q_final.y() * q_final.y() + q_final.z() * q_final.z() + q_final.w() * q_final.w()) < 0.1)
    {
        ROS_ERROR("Invalid quaternion, please use a 9-axis IMU!");
        ros::shutdown();
    }

    return imu_out;
}
```

and below is tranformation matrix for imu data from imu to camera 

```yaml
Imu_extrinsicTrans: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0, 0.0, 0.0]

# Should it in Camera Frame....
Imu_extrinsicRot: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  # data: [-1, 0, 0, 0, 0, 1, 0, -1, 0] # created by chan
  # data: [-1, 0, 0, 0, 0, 1, 0, 1, 0] # test 
  data: [-1, 0, 0, 0, 1, 0, 0, 0, -1] # lio sam
  # data: [-1, 0, 0, 0, 1, 0, 0, 0, -1]
  # data : [0,0,-1,-1,0,0,0,1,0] # camera frame 
  # data : [0,0,1,1,0,0,0,1,0] # after checking orientation of imu
```

can you help me out what should i try or change?

thank you for your hard work
