### ISSUE TITLE
GoPro08

### ISSUE THREAD

**Issue by SnkFst** [HKUST-Aerial-Robotics/VINS-Fusion#209]
Hello, 

i used https://github.com/AutonomousFieldRoboticsLab/gopro_ros to create out of an GoPro 08 MP4 file a bag for VINS (it has images and imu data). After i fixed some issues with the topics and types to the right one (compressed_images to normal images in my bag file) and wrote a new config file (so topics for vins and my bag match) i played my bag with vins on UBUNTU 18.04 . It works, so my imu and images are read with the configfile but the data don't get initializedand in my rviz windows it only shows the pictures and not the map with pointcloud. i don't know whtas the issue because i checked everything an it seems right. 
My bag fil:  
```bash
rosbag info converted.bag
path:        converted.bag
version:     2.0
duration:    27.0s
start:       May 04 2023 20:47:40.11 (1683226060.11)
end:         May 04 2023 20:48:07.13 (1683226087.13)
size:        4.7 GB
messages:    6995
compression: none [1621/1621 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu   [6a62c6daae103f4ff57a132d6f95cec2]
topics:      /gopro/image_raw/compressed   1620 msgs    : sensor_msgs/Image
             /gopro/imu                    5375 msgs    : sensor_msgs/Imu
```
my config file:
```yaml
 %YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/gopro/imu"
image0_topic: "/gopro/image_raw/compressed"
output_path: "~/output/"

cam0_calib: "cam0_GoPro8.yaml"
image_width: 2704
image_height: 1520
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
           0, 1, 0,  0,
          0, 0, 1, 0,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
```

So that are the important information. If you can help i would be very grateful. 
Greetings
