### ISSUE TITLE
Using oak-D pro W to do VIO with Vins-Fusion ROS pkg problem

### ISSUE THREAD

**Issue by Yousef19986** [HKUST-Aerial-Robotics/VINS-Fusion#241]
Hi all,

I have oak d pro W camera I want to use it with VINS-fusion in order to do VIO but the problem when it starts it works fine but when i start moving the odometery frame starts going everwhere and drifting very far even if stop moving the camera.

https://drive.google.com/file/d/1DvuOQYZ5g-vEMyqDJ1AvA3atwCJUSspy/view?usp=sharing

I would appreciate if there is someone can help me. 

This is my config file :
```
%YAML:1.0

#common parameters
imu: 1
num_of_cam: 2

imu_topic: "/stereo_inertial_publisher/imu"
image0_topic: "/stereo_inertial_publisher/left/image_rect"
image1_topic: "/stereo_inertial_publisher/right/image_rect"
output_path: "/home/pi/Documents"

cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 4056  # updated based on OAK-D Pro W specs
image_height: 3040 # updated based on OAK-D Pro W specs

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0  # Disable extrinsic estimation, use provided values

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 0, 0, 1, 0,
          -1, 0, 0, 0.0375,
          0, -1, 0, 0,
          0, 0, 0, 1 ]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 0, 0, 1, 0,
          -1, 0, 0, -0.0375,
          0, -1, 0, 0,
          0, 0, 0, 1 ]

#Multiple thread support
multiple_thread: 2

#feature tracker parameters
max_cnt: 200  # slightly reduced for stability
min_dist: 20   # further reduced for higher resolution, adjust if needed
freq: 120      # matches max framerate of OAK-D Pro W
F_threshold: 1.0
show_track: 1
flow_back: 1

#optimization parameters
max_solver_time: 0.04 # Increased solver time for better convergence
max_num_iterations: 5   # Increased iterations for better convergence 
keyframe_parallax: 10.0 # Reduced parallax for more frequent keyframes

#imu parameters
acc_n: 0.5     # Reduced noise values for OAK-D Pro W IMU
gyr_n: 0.02    # Reduced noise values for OAK-D Pro W IMU
acc_w: 0.002   # Reduced random walk for OAK-D Pro W IMU
gyr_w: 1.0e-05 # Reduced random walk for OAK-D Pro W IMU
g_norm: 9.805

#unsynchronization parameters
estimate_td: 0 # Disable time-offset estimation 
td: 0.0       # Set time-offset to zero

#loop closure parameters
load_previous_pose_graph: 0
pose_graph_save_path: "/home/pi/Documents"
save_image: 0

```

and this is my left eye config file :
```
%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 800
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 832.2688598632812
   fy: 835.7731323242188
   cx: 625.9611206054688
   cy: 354.8282775878906
```

and this is my right config file :
```
%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 800
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 841.0867309570312
   fy: 844.6397705078125
   cx: 617.4251708984375
   cy: 354.2491760253906
   
  ```
